trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "client_id=$(client_id) client_secret=$(client_secret) ssh_public_key=$(publickey.secureFilePath)"
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa1.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-RM-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'neilcloud-tstate-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'neilcloudtfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform-dev.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'Azure-RM-service-connection'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'Azure-RM-service-connection'
